return {
  "ThePrimeagen/harpoon",

  config = function()
    vim.keymap.set("n", "<leader>hh", function()
      require("harpoon.ui").toggle_quick_menu()
    end, { desc = "Harpoon Menu" })
    vim.keymap.set("n", "<leader>hf", function()
      require("harpoon.mark").add_file()
    end, { desc = "Harpoon Add File" })
    vim.keymap.set("n", "<leader>hn", function()
      require("harpoon.ui").nav_next()
    end, { desc = "Harpoon Next" })
    vim.keymap.set("n", "<leader>hp", function()
      require("harpoon.ui").nav_prev()
    end, { desc = "Harpoon Previous" })
    vim.keymap.set("n", "<leader>h1", function()
      require("harpoon.ui").nav_file(1)
    end, { desc = "Harpoon 1" })
    vim.keymap.set("n", "<leader>h2", function()
      require("harpoon.ui").nav_file(2)
    end, { desc = "Harpoon 2" })
    vim.keymap.set("n", "<leader>h3", function()
      require("harpoon.ui").nav_file(3)
    end, { desc = "Harpoon 3" })
    vim.keymap.set("n", "<leader>h4", function()
      require("harpoon.ui").nav_file(4)
    end, { desc = "Harpoon 4" })
    vim.keymap.set("n", "<leader>h5", function()
      require("harpoon.ui").nav_file(5)
    end, { desc = "Harpoon 5" })
  end,
}
