return {
	"ThePrimeagen/harpoon",

	config = function()
		vim.keymap.set("n", "<leader>hh", function()
			require("harpoon.ui").toggle_quick_menu()
		end)
		vim.keymap.set("n", "<leader>hf", function()
			require("harpoon.mark").add_file()
		end)
		vim.keymap.set("n", "<leader>hn", function()
			require("harpoon.ui").nav_next()
		end)
		vim.keymap.set("n", "<leader>hp", function()
			require("harpoon.ui").nav_prev()
		end)
		vim.keymap.set("n", "<leader>h1", function()
			require("harpoon.ui").nav_file(1)
		end)
		vim.keymap.set("n", "<leader>h2", function()
			require("harpoon.ui").nav_file(2)
		end)
		vim.keymap.set("n", "<leader>h3", function()
			require("harpoon.ui").nav_file(3)
		end)
		vim.keymap.set("n", "<leader>h4", function()
			require("harpoon.ui").nav_file(4)
		end)
		vim.keymap.set("n", "<leader>h5", function()
			require("harpoon.ui").nav_file(5)
		end)
	end,
}
